// Generated by gencpp from file tm_motion/ActionFeedback.msg
// DO NOT EDIT!


#ifndef TM_MOTION_MESSAGE_ACTIONFEEDBACK_H
#define TM_MOTION_MESSAGE_ACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tm_motion
{
template <class ContainerAllocator>
struct ActionFeedback_
{
  typedef ActionFeedback_<ContainerAllocator> Type;

  ActionFeedback_()
    : received_data()  {
    }
  ActionFeedback_(const ContainerAllocator& _alloc)
    : received_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _received_data_type;
  _received_data_type received_data;





  typedef boost::shared_ptr< ::tm_motion::ActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_motion::ActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ActionFeedback_

typedef ::tm_motion::ActionFeedback_<std::allocator<void> > ActionFeedback;

typedef boost::shared_ptr< ::tm_motion::ActionFeedback > ActionFeedbackPtr;
typedef boost::shared_ptr< ::tm_motion::ActionFeedback const> ActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_motion::ActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_motion::ActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tm_motion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'tm_motion': ['/home/tthmatt/Omron_TM_ROS/devel/.private/tm_motion/share/tm_motion/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tm_motion::ActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_motion::ActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_motion::ActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_motion::ActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_motion::ActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_motion::ActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_motion::ActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0db3bc19eeede9e4ee493e93f03da761";
  }

  static const char* value(const ::tm_motion::ActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0db3bc19eeede9e4ULL;
  static const uint64_t static_value2 = 0xee493e93f03da761ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_motion::ActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_motion/ActionFeedback";
  }

  static const char* value(const ::tm_motion::ActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_motion::ActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"string received_data\n"
"\n"
;
  }

  static const char* value(const ::tm_motion::ActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_motion::ActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_motion::ActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_motion::ActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "received_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.received_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MOTION_MESSAGE_ACTIONFEEDBACK_H
