// Generated by gencpp from file tm_motion/TmMotionResponse.msg
// DO NOT EDIT!


#ifndef TM_MOTION_MESSAGE_TMMOTIONRESPONSE_H
#define TM_MOTION_MESSAGE_TMMOTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tm_motion
{
template <class ContainerAllocator>
struct TmMotionResponse_
{
  typedef TmMotionResponse_<ContainerAllocator> Type;

  TmMotionResponse_()
    : device()  {
    }
  TmMotionResponse_(const ContainerAllocator& _alloc)
    : device(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _device_type;
  _device_type device;





  typedef boost::shared_ptr< ::tm_motion::TmMotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_motion::TmMotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TmMotionResponse_

typedef ::tm_motion::TmMotionResponse_<std::allocator<void> > TmMotionResponse;

typedef boost::shared_ptr< ::tm_motion::TmMotionResponse > TmMotionResponsePtr;
typedef boost::shared_ptr< ::tm_motion::TmMotionResponse const> TmMotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_motion::TmMotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_motion::TmMotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tm_motion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'tm_motion': ['/home/tthmatt/Omron-TM-ROS/devel/.private/tm_motion/share/tm_motion/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tm_motion::TmMotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_motion::TmMotionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_motion::TmMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_motion::TmMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_motion::TmMotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_motion::TmMotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_motion::TmMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25b143d1069c7861320973824c82b9d8";
  }

  static const char* value(const ::tm_motion::TmMotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25b143d1069c7861ULL;
  static const uint64_t static_value2 = 0x320973824c82b9d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_motion::TmMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_motion/TmMotionResponse";
  }

  static const char* value(const ::tm_motion::TmMotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_motion::TmMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string device\n"
"\n"
;
  }

  static const char* value(const ::tm_motion::TmMotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_motion::TmMotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TmMotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_motion::TmMotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_motion::TmMotionResponse_<ContainerAllocator>& v)
  {
    s << indent << "device: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.device);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MOTION_MESSAGE_TMMOTIONRESPONSE_H
