// Generated by gencpp from file tm_motion/TmMotionRequest.msg
// DO NOT EDIT!


#ifndef TM_MOTION_MESSAGE_TMMOTIONREQUEST_H
#define TM_MOTION_MESSAGE_TMMOTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tm_motion
{
template <class ContainerAllocator>
struct TmMotionRequest_
{
  typedef TmMotionRequest_<ContainerAllocator> Type;

  TmMotionRequest_()
    : a()  {
    }
  TmMotionRequest_(const ContainerAllocator& _alloc)
    : a(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::tm_motion::TmMotionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_motion::TmMotionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TmMotionRequest_

typedef ::tm_motion::TmMotionRequest_<std::allocator<void> > TmMotionRequest;

typedef boost::shared_ptr< ::tm_motion::TmMotionRequest > TmMotionRequestPtr;
typedef boost::shared_ptr< ::tm_motion::TmMotionRequest const> TmMotionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_motion::TmMotionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_motion::TmMotionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tm_motion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'tm_motion': ['/home/tthmatt/Omron-TM-ROS/devel/.private/tm_motion/share/tm_motion/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tm_motion::TmMotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_motion::TmMotionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_motion::TmMotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_motion::TmMotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_motion::TmMotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_motion::TmMotionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_motion::TmMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f6bc51cbf7510cc87897366558eca7b";
  }

  static const char* value(const ::tm_motion::TmMotionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f6bc51cbf7510ccULL;
  static const uint64_t static_value2 = 0x87897366558eca7bULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_motion::TmMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_motion/TmMotionRequest";
  }

  static const char* value(const ::tm_motion::TmMotionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_motion::TmMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] a\n"
;
  }

  static const char* value(const ::tm_motion::TmMotionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_motion::TmMotionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TmMotionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_motion::TmMotionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_motion::TmMotionRequest_<ContainerAllocator>& v)
  {
    s << indent << "a[]" << std::endl;
    for (size_t i = 0; i < v.a.size(); ++i)
    {
      s << indent << "  a[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.a[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MOTION_MESSAGE_TMMOTIONREQUEST_H
