(cl:in-package tm_motion-msg)
(cl:export '(GOAL_FUNCTION-VAL
          GOAL_FUNCTION
          GOAL_PARAM-VAL
          GOAL_PARAM
          GOAL_GOAL1-VAL
          GOAL_GOAL1
          GOAL_GOAL2-VAL
          GOAL_GOAL2
          GOAL_GOAL3-VAL
          GOAL_GOAL3
          GOAL_GOAL4-VAL
          GOAL_GOAL4
          GOAL_GOAL5-VAL
          GOAL_GOAL5
          GOAL_GOAL6-VAL
          GOAL_GOAL6
          GOAL_GOAL7-VAL
          GOAL_GOAL7
          GOAL_GOAL8-VAL
          GOAL_GOAL8
          GOAL_GOAL9-VAL
          GOAL_GOAL9
          GOAL_GOAL10-VAL
          GOAL_GOAL10
          GOAL_GOAL11-VAL
          GOAL_GOAL11
          GOAL_GOAL12-VAL
          GOAL_GOAL12
))