(cl:defpackage tm_motion-msg
  (:use )
  (:export
   "<ACTIONACTION>"
   "ACTIONACTION"
   "<ACTIONACTIONFEEDBACK>"
   "ACTIONACTIONFEEDBACK"
   "<ACTIONACTIONGOAL>"
   "ACTIONACTIONGOAL"
   "<ACTIONACTIONRESULT>"
   "ACTIONACTIONRESULT"
   "<ACTIONFEEDBACK>"
   "ACTIONFEEDBACK"
   "<ACTIONGOAL>"
   "ACTIONGOAL"
   "<ACTIONRESULT>"
   "ACTIONRESULT"
  ))

